<?php
declare(strict_types=1);
require_once __DIR__.'/../../controllers/EmployeeRecordsController.php';
$ctrl=new EmployeeRecordsController();
if($_SERVER['REQUEST_METHOD']==='POST'&&validate_csrf_token($_POST['csrf_token']??'')){$a=$_POST['form_action']??'';
    if($a==='update_task'){$ctrl->updateOnboardingTask((int)$_POST['task_id'],$_POST['status']);flash('success','Task updated.');redirect($_SERVER['PHP_SELF'].'?view='.$_POST['emp_id']);}
    if($a==='update_employee'){$f=['employment_status'=>$_POST['employment_status'],'employment_type'=>$_POST['employment_type'],'basic_salary'=>(float)$_POST['basic_salary']?:null];if(!empty($_POST['regularization_date']))$f['regularization_date']=$_POST['regularization_date'];$ctrl->update((int)$_POST['employee_id'],$f);flash('success','Updated.');redirect($_SERVER['PHP_SELF'].'?view='.$_POST['employee_id']);}
}
$filters=['status'=>$_GET['status']??'','department_id'=>$_GET['department_id']??'','search'=>$_GET['search']??''];$data=$ctrl->index($filters);$showView=isset($_GET['view']);$viewData=$showView?$ctrl->show((int)$_GET['view']):null;
$pageTitle='Employee Records';
include __DIR__.'/../../includes/layout_top.php';
?>
<?php if($showView&&$viewData):$e=$viewData['employee'];?>
<a href="?" class="uk-button uk-button-text uk-margin-bottom" style="font-size:.82rem">&larr; Back</a>
<div class="page-hd uk-margin-bottom"><h3><?=sanitize_output($e['first_name'].' '.$e['last_name'])?></h3><p><code><?=sanitize_output($e['employee_no'])?></code> &middot; <?=get_status_badge($e['employment_status'])?></p></div>
<div class="uk-grid-small" uk-grid>
<div class="uk-width-1-2@m"><div class="uk-card uk-card-default"><div class="uk-card-header"><h5 class="uk-margin-remove" style="font-weight:600;font-size:.9rem">Personal</h5></div><div class="uk-card-body" style="padding:16px 24px"><table class="uk-table uk-table-small uk-margin-remove" style="font-size:.84rem"><?php foreach(['Name'=>trim($e['first_name'].' '.($e['middle_name']??'').' '.$e['last_name']),'Email'=>$e['email']??'—','Phone'=>$e['phone']??'—','Birthday'=>format_date($e['date_of_birth']??''),'Gender'=>$e['gender']??'—','Address'=>$e['address']??'—'] as $k=>$v):?><tr><th style="width:30%;color:#999;border:0;padding:4px 0"><?=$k?></th><td style="border:0;padding:4px 0"><?=sanitize_output($v)?></td></tr><?php endforeach;?></table></div></div></div>
<div class="uk-width-1-2@m"><div class="uk-card uk-card-default"><div class="uk-card-header"><h5 class="uk-margin-remove" style="font-weight:600;font-size:.9rem">Employment</h5></div><div class="uk-card-body" style="padding:16px 24px"><table class="uk-table uk-table-small uk-margin-remove" style="font-size:.84rem"><?php foreach(['Position'=>$e['position_title']??'—','Department'=>$e['department_name']??'—','Type'=>$e['employment_type'],'Hired'=>format_date($e['date_hired']??''),'Salary'=>$e['basic_salary']?format_currency((float)$e['basic_salary']):'—'] as $k=>$v):?><tr><th style="width:30%;color:#999;border:0;padding:4px 0"><?=$k?></th><td style="border:0;padding:4px 0"><?=sanitize_output($v)?></td></tr><?php endforeach;?></table></div></div>
<div class="uk-card uk-card-default uk-margin-top"><div class="uk-card-header"><h5 class="uk-margin-remove" style="font-weight:600;font-size:.9rem">Quick Update</h5></div><div class="uk-card-body"><form method="POST" class="uk-grid-small uk-flex-bottom" uk-grid><input type="hidden" name="csrf_token" value="<?=generate_csrf_token()?>"><input type="hidden" name="form_action" value="update_employee"><input type="hidden" name="employee_id" value="<?=$e['employee_id']?>">
<div class="uk-width-1-3"><label class="uk-form-label">Status</label><select name="employment_status" class="uk-select uk-form-small"><?php foreach(['Active','Probationary','Regular','On Leave','Suspended','Resigned','Terminated','Retired'] as $ss):?><option <?=$e['employment_status']===$ss?'selected':''?>><?=$ss?></option><?php endforeach;?></select></div>
<div class="uk-width-1-3"><label class="uk-form-label">Type</label><select name="employment_type" class="uk-select uk-form-small"><?php foreach(['Full-Time','Part-Time','Contractual','Probationary'] as $tt):?><option <?=$e['employment_type']===$tt?'selected':''?>><?=$tt?></option><?php endforeach;?></select></div>
<div class="uk-width-1-4"><label class="uk-form-label">Salary</label><input type="number" name="basic_salary" class="uk-input uk-form-small" value="<?=$e['basic_salary']??''?>" step=".01"></div>
<div class="uk-width-auto"><input type="hidden" name="regularization_date" value="<?=$e['regularization_date']??''?>"><button class="uk-button uk-button-primary uk-button-small">Save</button></div>
</form></div></div></div></div>
<div class="uk-card uk-card-default uk-margin-top"><div class="uk-card-header"><h5 class="uk-margin-remove" style="font-weight:600;font-size:.9rem">Onboarding Tasks</h5></div><div class="uk-card-body np"><table class="uk-table uk-table-hover uk-table-middle uk-table-divider uk-margin-remove"><thead><tr><th>Task</th><th>Category</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach($viewData['onboarding_tasks'] as $t):?><tr><td style="font-size:.84rem"><?=sanitize_output($t['task_name'])?></td><td><span class="bd bd-secondary"><?=sanitize_output($t['category'])?></span></td><td style="font-size:.78rem"><?=format_date($t['due_date']??'')?></td><td><?=get_status_badge($t['status'])?></td>
<td><?php if($t['status']!=='Completed'):?><form method="POST"><input type="hidden" name="csrf_token" value="<?=generate_csrf_token()?>"><input type="hidden" name="form_action" value="update_task"><input type="hidden" name="task_id" value="<?=$t['task_id']?>"><input type="hidden" name="emp_id" value="<?=$e['employee_id']?>"><input type="hidden" name="status" value="Completed"><button class="uk-icon-link" uk-icon="icon:check;ratio:.8" style="color:#16a34a"></button></form><?php else:?><span uk-icon="icon:check;ratio:.8" style="color:#16a34a"></span><?php endif;?></td></tr><?php endforeach;?>
</tbody></table></div></div>
<?php else:?>
<div class="page-hd uk-flex uk-flex-between uk-flex-middle uk-margin-bottom"><div><h3>Employee Records</h3><p>Manage employee information &amp; onboarding</p></div><a href="<?=get_module_path('employee_records')?>/create.php" class="uk-button uk-button-primary uk-button-small"><span uk-icon="icon:plus;ratio:.8" class="uk-margin-small-right"></span>New Employee</a></div>
<div class="filter-bar uk-margin-bottom"><form class="uk-grid-small uk-flex-middle" uk-grid>
<div class="uk-width-1-4@m"><input type="text" name="search" class="uk-input uk-form-small" placeholder="Search..." value="<?=sanitize_output($filters['search'])?>"></div>
<div class="uk-width-1-5@m"><select name="status" class="uk-select uk-form-small"><option value="">All Status</option><?php foreach(['Active','Probationary','Regular','On Leave','Resigned'] as $ss):?><option <?=$filters['status']===$ss?'selected':''?>><?=$ss?></option><?php endforeach;?></select></div>
<div class="uk-width-auto"><button class="uk-button uk-button-default uk-button-small">Filter</button></div>
</form></div>
<div class="uk-card uk-card-default"><div class="uk-card-body np"><div class="uk-overflow-auto"><table class="uk-table uk-table-hover uk-table-middle uk-table-divider uk-margin-remove">
<thead><tr><th>Emp #</th><th>Name</th><th>Position</th><th>Dept</th><th>Status</th><th>Hired</th><th></th></tr></thead><tbody>
<?php foreach($data['employees'] as $emp):?><tr><td><code><?=sanitize_output($emp['employee_no'])?></code></td><td class="uk-text-bold" style="font-size:.84rem"><?=sanitize_output($emp['first_name'].' '.$emp['last_name'])?></td><td style="font-size:.82rem"><?=sanitize_output($emp['position_title']??'—')?></td><td style="font-size:.82rem"><?=sanitize_output($emp['department_name']??'—')?></td><td><?=get_status_badge($emp['employment_status'])?></td><td style="font-size:.78rem"><?=format_date($emp['date_hired']??'')?></td><td><a href="?view=<?=$emp['employee_id']?>" class="uk-icon-link" uk-icon="icon:chevron-right;ratio:.8"></a></td></tr><?php endforeach;?>
<?php if(empty($data['employees'])):?><tr><td colspan="7" class="uk-text-center uk-text-muted uk-padding-small">No employees</td></tr><?php endif;?>
</tbody></table></div></div></div>
<?php endif;?>
<?php include __DIR__.'/../../includes/layout_bottom.php';?>